#!/bin/bash
#SBATCH -t 00:10:00
#SBATCH -N 1
#SBATCH -n 23
#SBATCH -p normal
cd /home/vanes/cerebellum_prf/scripts
python create_predictions.py ---sub--- ---ses--- ---n_jobs--- ---mask_type--- ---postFix--- ---hrf_delay--- ---k---
